// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuiuktwwblstarfzapkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1aXVrdHd3YmxzdGFyZnphcGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDAyOTEsImV4cCI6MjA3MTU3NjI5MX0.HtCMnx1lXKXsQAbiNCLK5pPEyyP8fLUHjiZkW_NHDRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});